// Code generated by algokit-client-generator-go. DO NOT EDIT.
package statedecoding

import (
	"context"

	algokit "github.com/kylebeee/algokit-utils-go"
)

// Composer builds atomic transaction groups for the StateDecoding contract.
type Composer struct {
	client   *Client
	composer *algokit.TransactionComposer
}

// Init adds a init method call to the transaction group.
func (comp *Composer) Init(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "init" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// GetBox adds a getBox method call to the transaction group.
func (comp *Composer) GetBox(ctx context.Context, params algokit.CallParams[GetBoxArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceGetBox(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "getBox" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// DoNothing adds a doNothing method call to the transaction group.
func (comp *Composer) DoNothing(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "doNothing" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// RawState adds a rawState method call to the transaction group.
func (comp *Composer) RawState(ctx context.Context, params algokit.CallParams[RawStateArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceRawState(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "rawState" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// DecodeAppList adds a decodeAppList method call to the transaction group.
func (comp *Composer) DecodeAppList(ctx context.Context, params algokit.CallParams[DecodeAppListArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceDecodeAppList(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "decodeAppList" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// DecodeUint64 adds a decodeUint64 method call to the transaction group.
func (comp *Composer) DecodeUint64(ctx context.Context, params algokit.CallParams[DecodeUint64Args]) (*Composer, error) {
	methodArgs := argsToInterfaceDecodeUint64(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "decodeUint64" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// DecodeStaticArray adds a decodeStaticArray method call to the transaction group.
func (comp *Composer) DecodeStaticArray(ctx context.Context, params algokit.CallParams[DecodeStaticArrayArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceDecodeStaticArray(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "decodeStaticArray" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// CheckObjectAssignment adds a checkObjectAssignment method call to the transaction group.
func (comp *Composer) CheckObjectAssignment(ctx context.Context, params algokit.CallParams[CheckObjectAssignmentArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceCheckObjectAssignment(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "checkObjectAssignment" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// RetObject adds a retObject method call to the transaction group.
func (comp *Composer) RetObject(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "retObject" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// RetDecode adds a retDecode method call to the transaction group.
func (comp *Composer) RetDecode(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "retDecode" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// RetList adds a retList method call to the transaction group.
func (comp *Composer) RetList(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "retList" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// PercentileCheck adds a percentileCheck method call to the transaction group.
func (comp *Composer) PercentileCheck(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "percentileCheck" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// BigLoop adds a bigLoop method call to the transaction group.
func (comp *Composer) BigLoop(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "bigLoop" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// BigCLoop adds a bigCLoop method call to the transaction group.
func (comp *Composer) BigCLoop(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "bigCLoop" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// Nullun adds a nullun method call to the transaction group.
func (comp *Composer) Nullun(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "nullun" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// DynamicArrayOfDynamicArrays adds a dynamicArrayOfDynamicArrays method call to the transaction group.
func (comp *Composer) DynamicArrayOfDynamicArrays(ctx context.Context, params algokit.CallParams[DynamicArrayOfDynamicArraysArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceDynamicArrayOfDynamicArrays(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "dynamicArrayOfDynamicArrays" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SubTest adds a subTest method call to the transaction group.
func (comp *Composer) SubTest(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "subTest" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// ShadowTest adds a shadowTest method call to the transaction group.
func (comp *Composer) ShadowTest(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "shadowTest" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// BoxSetTest adds a boxSetTest method call to the transaction group.
func (comp *Composer) BoxSetTest(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "boxSetTest" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// PaddedBytes adds a paddedBytes method call to the transaction group.
func (comp *Composer) PaddedBytes(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "paddedBytes" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// Send executes the composed transaction group and waits for confirmation.
func (comp *Composer) Send(ctx context.Context) (*algokit.ComposerExecuteResult, error) {
	return comp.composer.Execute(ctx, 5)
}
