// Code generated by algokit-client-generator-go. DO NOT EDIT.
package statedecoding

import (
	"github.com/algorand/go-algorand-sdk/v2/types"
	algokit "github.com/kylebeee/algokit-utils-go"
)

// RandoObject is a generated struct type.
type RandoObject struct {
	A uint64 `json:"a"`
	B uint64 `json:"b"`
}

// ShadowTestResult is a generated struct type.
type ShadowTestResult struct {
	A     bool `json:"a"`
	B     bool `json:"b"`
	C     bool `json:"c"`
	Valid bool `json:"valid"`
}

// AppList is a generated struct type.
type AppList struct {
	One      uint64 `json:"one"`
	Two      uint64 `json:"two"`
	Three    uint64 `json:"three"`
	Four     uint64 `json:"four"`
	Five     uint64 `json:"five"`
	Six      uint64 `json:"six"`
	Seven    uint64 `json:"seven"`
	Eight    uint64 `json:"eight"`
	Nine     uint64 `json:"nine"`
	Ten      uint64 `json:"ten"`
	Eleven   uint64 `json:"eleven"`
	Twelve   uint64 `json:"twelve"`
	Thirteen uint64 `json:"thirteen"`
	Fourteen uint64 `json:"fourteen"`
	Fifteen  uint64 `json:"fifteen"`
}

// RandoStruct is a generated struct type.
type RandoStruct struct {
	A uint64 `json:"a"`
	B uint64 `json:"b"`
}

// RandoComplexObject is a generated struct type.
type RandoComplexObject struct {
	A uint64        `json:"a"`
	B types.Address `json:"b"`
	C []uint64      `json:"c"`
}

// GetBoxArgs holds the arguments for the getBox method.
type GetBoxArgs struct {
	Offset uint64
}

// GetBoxMethodResult holds the result of calling getBox.
type GetBoxMethodResult struct {
	algokit.SendAppTransactionResult
	Return []byte
}

// RawStateArgs holds the arguments for the rawState method.
type RawStateArgs struct {
	App uint64
}

// RawStateMethodResult holds the result of calling rawState.
type RawStateMethodResult struct {
	algokit.SendAppTransactionResult
	Return []byte
}

// DecodeAppListArgs holds the arguments for the decodeAppList method.
type DecodeAppListArgs struct {
	App uint64
}

// DecodeAppListMethodResult holds the result of calling decodeAppList.
type DecodeAppListMethodResult struct {
	algokit.SendAppTransactionResult
	Return AppList
}

// DecodeUint64Args holds the arguments for the decodeUint64 method.
type DecodeUint64Args struct {
	App uint64
}

// DecodeUint64MethodResult holds the result of calling decodeUint64.
type DecodeUint64MethodResult struct {
	algokit.SendAppTransactionResult
	Return uint64
}

// DecodeStaticArrayArgs holds the arguments for the decodeStaticArray method.
type DecodeStaticArrayArgs struct {
	App uint64
}

// DecodeStaticArrayMethodResult holds the result of calling decodeStaticArray.
type DecodeStaticArrayMethodResult struct {
	algokit.SendAppTransactionResult
	Return AppList
}

// CheckObjectAssignmentArgs holds the arguments for the checkObjectAssignment method.
type CheckObjectAssignmentArgs struct {
	A uint64
	B uint64
}

// CheckObjectAssignmentMethodResult holds the result of calling checkObjectAssignment.
type CheckObjectAssignmentMethodResult struct {
	algokit.SendAppTransactionResult
	Return RandoStruct
}

// RetObjectMethodResult holds the result of calling retObject.
type RetObjectMethodResult struct {
	algokit.SendAppTransactionResult
	Return RandoObject
}

// RetDecodeMethodResult holds the result of calling retDecode.
type RetDecodeMethodResult struct {
	algokit.SendAppTransactionResult
	Return RandoComplexObject
}

// RetListMethodResult holds the result of calling retList.
type RetListMethodResult struct {
	algokit.SendAppTransactionResult
	Return [][]interface{}
}

// PercentileCheckMethodResult holds the result of calling percentileCheck.
type PercentileCheckMethodResult struct {
	algokit.SendAppTransactionResult
	Return [5]uint64
}

// BigLoopMethodResult holds the result of calling bigLoop.
type BigLoopMethodResult struct {
	algokit.SendAppTransactionResult
	Return uint64
}

// BigCLoopMethodResult holds the result of calling bigCLoop.
type BigCLoopMethodResult struct {
	algokit.SendAppTransactionResult
	Return []interface{}
}

// DynamicArrayOfDynamicArraysArgs holds the arguments for the dynamicArrayOfDynamicArrays method.
type DynamicArrayOfDynamicArraysArgs struct {
	A uint64
	B [][]interface{}
	C types.Address
}

// DynamicArrayOfDynamicArraysMethodResult holds the result of calling dynamicArrayOfDynamicArrays.
type DynamicArrayOfDynamicArraysMethodResult struct {
	algokit.SendAppTransactionResult
	Return []uint64
}

// SubTestMethodResult holds the result of calling subTest.
type SubTestMethodResult struct {
	algokit.SendAppTransactionResult
	Return [5]uint64
}

// ShadowTestMethodResult holds the result of calling shadowTest.
type ShadowTestMethodResult struct {
	algokit.SendAppTransactionResult
	Return ShadowTestResult
}

// PaddedBytesMethodResult holds the result of calling paddedBytes.
type PaddedBytesMethodResult struct {
	algokit.SendAppTransactionResult
	Return [32]byte
}
