// Code generated by algokit-client-generator-go. DO NOT EDIT.
package applicationequality

import (
	"context"

	algokit "github.com/kylebeee/algokit-utils-go"
)

// Composer builds atomic transaction groups for the ApplicationEquality contract.
type Composer struct {
	client   *Client
	composer *algokit.TransactionComposer
}

// DoNothing adds a doNothing method call to the transaction group.
func (comp *Composer) DoNothing(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "doNothing" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// AppEquals adds a appEquals method call to the transaction group.
func (comp *Composer) AppEquals(ctx context.Context, params algokit.CallParams[AppEqualsArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceAppEquals(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "appEquals" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// Send executes the composed transaction group and waits for confirmation.
func (comp *Composer) Send(ctx context.Context) (*algokit.ComposerExecuteResult, error) {
	return comp.composer.Execute(ctx, 5)
}
