// Code generated by algokit-client-generator-go. DO NOT EDIT.
package xgovregistry

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/algorand/go-algorand-sdk/v2/types"
	algokit "github.com/kylebeee/algokit-utils-go"
)

// Client is a typed client for the XGovRegistry smart contract.
type Client struct {
	AppClient *algokit.AppClient
}

// NewClient creates a new typed client wrapping an existing AppClient.
func NewClient(appClient *algokit.AppClient) *Client {
	return &Client{AppClient: appClient}
}

// NewClientFromSpec creates a new typed client from AppClientParams.
func NewClientFromSpec(params algokit.AppClientParams) (*Client, error) {
	if params.AppSpec == nil {
		spec, err := GetAppSpec()
		if err != nil {
			return nil, err
		}
		params.AppSpec = spec
	}
	appClient, err := algokit.NewAppClient(params)
	if err != nil {
		return nil, err
	}
	return &Client{AppClient: appClient}, nil
}

// GetAppSpec returns the parsed ARC-56 app specification for this contract.
func GetAppSpec() (*algokit.Arc56Contract, error) {
	return algokit.ParseArc56Contract([]byte(AppSpecJSON))
}

// AppID returns the application ID.
func (c *Client) AppID() uint64 {
	return c.AppClient.AppID()
}

// AppAddress returns the application's escrow address.
func (c *Client) AppAddress() types.Address {
	return c.AppClient.AppAddress()
}

// NewGroup creates a new Composer for building atomic transaction groups.
func (c *Client) NewGroup() *Composer {
	return &Composer{
		client:   c,
		composer: c.AppClient.NewComposer(),
	}
}

// SendInitProposalContract calls the init_proposal_contract ABI method and waits for confirmation.
// Initializes the Proposal Approval Program contract.
func (c *Client) SendInitProposalContract(ctx context.Context, params algokit.CallParams[InitProposalContractArgs]) error {
	methodArgs := argsToInterfaceInitProposalContract(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "init_proposal_contract",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendLoadProposalContract calls the load_proposal_contract ABI method and waits for confirmation.
// Loads the Proposal Approval Program contract.
func (c *Client) SendLoadProposalContract(ctx context.Context, params algokit.CallParams[LoadProposalContractArgs]) error {
	methodArgs := argsToInterfaceLoadProposalContract(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "load_proposal_contract",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendDeleteProposalContractBox calls the delete_proposal_contract_box ABI method and waits for confirmation.
// Deletes the Proposal Approval Program contract box.
func (c *Client) SendDeleteProposalContractBox(ctx context.Context) error {
	methodArgs := []interface{}(nil)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName: "delete_proposal_contract_box",
		MethodArgs: methodArgs,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendPauseRegistry calls the pause_registry ABI method and waits for confirmation.
// Pauses the xGov Registry non-administrative methods.
func (c *Client) SendPauseRegistry(ctx context.Context) error {
	methodArgs := []interface{}(nil)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName: "pause_registry",
		MethodArgs: methodArgs,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendPauseProposals calls the pause_proposals ABI method and waits for confirmation.
// Pauses the creation of new Proposals.
func (c *Client) SendPauseProposals(ctx context.Context) error {
	methodArgs := []interface{}(nil)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName: "pause_proposals",
		MethodArgs: methodArgs,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendResumeRegistry calls the resume_registry ABI method and waits for confirmation.
// Resumes the xGov Registry non-administrative methods.
func (c *Client) SendResumeRegistry(ctx context.Context) error {
	methodArgs := []interface{}(nil)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName: "resume_registry",
		MethodArgs: methodArgs,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendResumeProposals calls the resume_proposals ABI method and waits for confirmation.
// Resumes the creation of new Proposals.
func (c *Client) SendResumeProposals(ctx context.Context) error {
	methodArgs := []interface{}(nil)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName: "resume_proposals",
		MethodArgs: methodArgs,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSetXgovManager calls the set_xgov_manager ABI method and waits for confirmation.
// Sets the xGov Manager.
func (c *Client) SendSetXgovManager(ctx context.Context, params algokit.CallParams[SetXgovManagerArgs]) error {
	methodArgs := argsToInterfaceSetXgovManager(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "set_xgov_manager",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSetPayor calls the set_payor ABI method and waits for confirmation.
// Sets the xGov Payor.
func (c *Client) SendSetPayor(ctx context.Context, params algokit.CallParams[SetPayorArgs]) error {
	methodArgs := argsToInterfaceSetPayor(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "set_payor",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSetXgovCouncil calls the set_xgov_council ABI method and waits for confirmation.
// Sets the xGov Council.
func (c *Client) SendSetXgovCouncil(ctx context.Context, params algokit.CallParams[SetXgovCouncilArgs]) error {
	methodArgs := argsToInterfaceSetXgovCouncil(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "set_xgov_council",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSetXgovSubscriber calls the set_xgov_subscriber ABI method and waits for confirmation.
// Sets the xGov Subscriber.
func (c *Client) SendSetXgovSubscriber(ctx context.Context, params algokit.CallParams[SetXgovSubscriberArgs]) error {
	methodArgs := argsToInterfaceSetXgovSubscriber(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "set_xgov_subscriber",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSetKycProvider calls the set_kyc_provider ABI method and waits for confirmation.
// Sets the KYC provider.
func (c *Client) SendSetKycProvider(ctx context.Context, params algokit.CallParams[SetKycProviderArgs]) error {
	methodArgs := argsToInterfaceSetKycProvider(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "set_kyc_provider",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSetCommitteeManager calls the set_committee_manager ABI method and waits for confirmation.
// Sets the Committee Manager.
func (c *Client) SendSetCommitteeManager(ctx context.Context, params algokit.CallParams[SetCommitteeManagerArgs]) error {
	methodArgs := argsToInterfaceSetCommitteeManager(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "set_committee_manager",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSetXgovDaemon calls the set_xgov_daemon ABI method and waits for confirmation.
// Sets the xGov Daemon.
func (c *Client) SendSetXgovDaemon(ctx context.Context, params algokit.CallParams[SetXgovDaemonArgs]) error {
	methodArgs := argsToInterfaceSetXgovDaemon(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "set_xgov_daemon",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendConfigXgovRegistry calls the config_xgov_registry ABI method and waits for confirmation.
// Sets the configuration of the xGov Registry.
func (c *Client) SendConfigXgovRegistry(ctx context.Context, params algokit.CallParams[ConfigXgovRegistryArgs]) error {
	methodArgs := argsToInterfaceConfigXgovRegistry(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "config_xgov_registry",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSubscribeXgov calls the subscribe_xgov ABI method and waits for confirmation.
// Subscribes the sender to being an xGov.
func (c *Client) SendSubscribeXgov(ctx context.Context, params algokit.CallParams[SubscribeXgovArgs]) error {
	methodArgs := argsToInterfaceSubscribeXgov(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "subscribe_xgov",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendUnsubscribeXgov calls the unsubscribe_xgov ABI method and waits for confirmation.
// Unsubscribes the sender from being an xGov.
func (c *Client) SendUnsubscribeXgov(ctx context.Context) error {
	methodArgs := []interface{}(nil)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName: "unsubscribe_xgov",
		MethodArgs: methodArgs,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendUnsubscribeAbsentee calls the unsubscribe_absentee ABI method and waits for confirmation.
// Unsubscribes an absentee xGov. This is a temporary method used only for the
// first absentees removal at the inception of the absenteeism penalty.
func (c *Client) SendUnsubscribeAbsentee(ctx context.Context, params algokit.CallParams[UnsubscribeAbsenteeArgs]) error {
	methodArgs := argsToInterfaceUnsubscribeAbsentee(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "unsubscribe_absentee",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendRequestSubscribeXgov calls the request_subscribe_xgov ABI method and waits for confirmation.
// Requests to subscribe to the xGov.
func (c *Client) SendRequestSubscribeXgov(ctx context.Context, params algokit.CallParams[RequestSubscribeXgovArgs]) error {
	methodArgs := argsToInterfaceRequestSubscribeXgov(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "request_subscribe_xgov",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendApproveSubscribeXgov calls the approve_subscribe_xgov ABI method and waits for confirmation.
// Approves a subscribe request to xGov.
func (c *Client) SendApproveSubscribeXgov(ctx context.Context, params algokit.CallParams[ApproveSubscribeXgovArgs]) error {
	methodArgs := argsToInterfaceApproveSubscribeXgov(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "approve_subscribe_xgov",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendRejectSubscribeXgov calls the reject_subscribe_xgov ABI method and waits for confirmation.
// Rejects a subscribe request to xGov.
func (c *Client) SendRejectSubscribeXgov(ctx context.Context, params algokit.CallParams[RejectSubscribeXgovArgs]) error {
	methodArgs := argsToInterfaceRejectSubscribeXgov(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "reject_subscribe_xgov",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendRequestUnsubscribeXgov calls the request_unsubscribe_xgov ABI method and waits for confirmation.
// Requests to unsubscribe from the xGov.
func (c *Client) SendRequestUnsubscribeXgov(ctx context.Context, params algokit.CallParams[RequestUnsubscribeXgovArgs]) error {
	methodArgs := argsToInterfaceRequestUnsubscribeXgov(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "request_unsubscribe_xgov",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendApproveUnsubscribeXgov calls the approve_unsubscribe_xgov ABI method and waits for confirmation.
// Approves a request to unsubscribe from xGov.
func (c *Client) SendApproveUnsubscribeXgov(ctx context.Context, params algokit.CallParams[ApproveUnsubscribeXgovArgs]) error {
	methodArgs := argsToInterfaceApproveUnsubscribeXgov(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "approve_unsubscribe_xgov",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendRejectUnsubscribeXgov calls the reject_unsubscribe_xgov ABI method and waits for confirmation.
// Rejects a request to unsubscribe from xGov.
func (c *Client) SendRejectUnsubscribeXgov(ctx context.Context, params algokit.CallParams[RejectUnsubscribeXgovArgs]) error {
	methodArgs := argsToInterfaceRejectUnsubscribeXgov(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "reject_unsubscribe_xgov",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSetVotingAccount calls the set_voting_account ABI method and waits for confirmation.
// Sets the Voting Address for the xGov.
func (c *Client) SendSetVotingAccount(ctx context.Context, params algokit.CallParams[SetVotingAccountArgs]) error {
	methodArgs := argsToInterfaceSetVotingAccount(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "set_voting_account",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSubscribeProposer calls the subscribe_proposer ABI method and waits for confirmation.
// Subscribes the sender to being a Proposer.
func (c *Client) SendSubscribeProposer(ctx context.Context, params algokit.CallParams[SubscribeProposerArgs]) error {
	methodArgs := argsToInterfaceSubscribeProposer(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "subscribe_proposer",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendSetProposerKyc calls the set_proposer_kyc ABI method and waits for confirmation.
// Sets a proposer's KYC status.
func (c *Client) SendSetProposerKyc(ctx context.Context, params algokit.CallParams[SetProposerKycArgs]) error {
	methodArgs := argsToInterfaceSetProposerKyc(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "set_proposer_kyc",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendDeclareCommittee calls the declare_committee ABI method and waits for confirmation.
// Sets the xGov Committee in charge.
func (c *Client) SendDeclareCommittee(ctx context.Context, params algokit.CallParams[DeclareCommitteeArgs]) error {
	methodArgs := argsToInterfaceDeclareCommittee(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "declare_committee",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendOpenProposal calls the open_proposal ABI method and waits for confirmation.
// Creates a new Proposal.
func (c *Client) SendOpenProposal(ctx context.Context, params algokit.CallParams[OpenProposalArgs]) (*OpenProposalMethodResult, error) {
	methodArgs := argsToInterfaceOpenProposal(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "open_proposal",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return nil, err
	}

	typedResult := &OpenProposalMethodResult{
		SendAppTransactionResult: *result,
	}

	if result.ABIReturn != nil {
		if val, ok := result.ABIReturn.(uint64); ok {
			typedResult.Return = val
		}
	}

	return typedResult, nil
}

// SendVoteProposal calls the vote_proposal ABI method and waits for confirmation.
// Votes on a Proposal.
func (c *Client) SendVoteProposal(ctx context.Context, params algokit.CallParams[VoteProposalArgs]) error {
	methodArgs := argsToInterfaceVoteProposal(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "vote_proposal",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendUnassignAbsenteeFromProposal calls the unassign_absentee_from_proposal ABI method and waits for confirmation.
// Unassign absentees from a scrutinized Proposal.
func (c *Client) SendUnassignAbsenteeFromProposal(ctx context.Context, params algokit.CallParams[UnassignAbsenteeFromProposalArgs]) error {
	methodArgs := argsToInterfaceUnassignAbsenteeFromProposal(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "unassign_absentee_from_proposal",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendPayGrantProposal calls the pay_grant_proposal ABI method and waits for confirmation.
// Disburses the funds for an approved Proposal.
func (c *Client) SendPayGrantProposal(ctx context.Context, params algokit.CallParams[PayGrantProposalArgs]) error {
	methodArgs := argsToInterfacePayGrantProposal(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "pay_grant_proposal",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendFinalizeProposal calls the finalize_proposal ABI method and waits for confirmation.
// Finalize a Proposal.
func (c *Client) SendFinalizeProposal(ctx context.Context, params algokit.CallParams[FinalizeProposalArgs]) error {
	methodArgs := argsToInterfaceFinalizeProposal(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "finalize_proposal",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendDropProposal calls the drop_proposal ABI method and waits for confirmation.
// Drops a Proposal.
func (c *Client) SendDropProposal(ctx context.Context, params algokit.CallParams[DropProposalArgs]) error {
	methodArgs := argsToInterfaceDropProposal(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "drop_proposal",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendDepositFunds calls the deposit_funds ABI method and waits for confirmation.
// Deposits xGov program funds into the xGov Treasury (xGov Registry Account).
func (c *Client) SendDepositFunds(ctx context.Context, params algokit.CallParams[DepositFundsArgs]) error {
	methodArgs := argsToInterfaceDepositFunds(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "deposit_funds",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendWithdrawFunds calls the withdraw_funds ABI method and waits for confirmation.
// Remove xGov program funds from the xGov Treasury (xGov Registry Account).
func (c *Client) SendWithdrawFunds(ctx context.Context, params algokit.CallParams[WithdrawFundsArgs]) error {
	methodArgs := argsToInterfaceWithdrawFunds(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "withdraw_funds",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendWithdrawBalance calls the withdraw_balance ABI method and waits for confirmation.
// Withdraw outstanding Algos, excluding MBR and outstanding funds, from the xGov Registry.
func (c *Client) SendWithdrawBalance(ctx context.Context) error {
	methodArgs := []interface{}(nil)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName: "withdraw_balance",
		MethodArgs: methodArgs,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendGetState calls the get_state ABI method and waits for confirmation.
// Returns the xGov Registry state.
func (c *Client) SendGetState(ctx context.Context) (*GetStateMethodResult, error) {
	methodArgs := []interface{}(nil)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName: "get_state",
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}

	typedResult := &GetStateMethodResult{
		SendAppTransactionResult: *result,
	}

	if result.ABIReturn != nil {
		if vals, ok := result.ABIReturn.([]interface{}); ok {
			if err := algokit.TupleToStruct(vals, &typedResult.Return); err != nil {
				return nil, fmt.Errorf("failed to decode return: %w", err)
			}
		}
	}

	return typedResult, nil
}

// SendGetXgovBox calls the get_xgov_box ABI method and waits for confirmation.
// Returns the xGov box for the given address.
func (c *Client) SendGetXgovBox(ctx context.Context, params algokit.CallParams[GetXgovBoxArgs]) (*GetXgovBoxMethodResult, error) {
	methodArgs := argsToInterfaceGetXgovBox(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "get_xgov_box",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return nil, err
	}

	typedResult := &GetXgovBoxMethodResult{
		SendAppTransactionResult: *result,
	}

	if result.ABIReturn != nil {
		if val, ok := result.ABIReturn.([]interface{}); ok {
			typedResult.Return = val
		}
	}

	return typedResult, nil
}

// SendGetProposerBox calls the get_proposer_box ABI method and waits for confirmation.
// Returns the Proposer box for the given address.
func (c *Client) SendGetProposerBox(ctx context.Context, params algokit.CallParams[GetProposerBoxArgs]) (*GetProposerBoxMethodResult, error) {
	methodArgs := argsToInterfaceGetProposerBox(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "get_proposer_box",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return nil, err
	}

	typedResult := &GetProposerBoxMethodResult{
		SendAppTransactionResult: *result,
	}

	if result.ABIReturn != nil {
		if val, ok := result.ABIReturn.([]interface{}); ok {
			typedResult.Return = val
		}
	}

	return typedResult, nil
}

// SendGetRequestBox calls the get_request_box ABI method and waits for confirmation.
// Returns the xGov subscribe request box for the given request ID.
func (c *Client) SendGetRequestBox(ctx context.Context, params algokit.CallParams[GetRequestBoxArgs]) (*GetRequestBoxMethodResult, error) {
	methodArgs := argsToInterfaceGetRequestBox(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "get_request_box",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return nil, err
	}

	typedResult := &GetRequestBoxMethodResult{
		SendAppTransactionResult: *result,
	}

	if result.ABIReturn != nil {
		if val, ok := result.ABIReturn.([]interface{}); ok {
			typedResult.Return = val
		}
	}

	return typedResult, nil
}

// SendGetRequestUnsubscribeBox calls the get_request_unsubscribe_box ABI method and waits for confirmation.
// Returns the xGov unsubscribe request box for the given unsubscribe request ID.
func (c *Client) SendGetRequestUnsubscribeBox(ctx context.Context, params algokit.CallParams[GetRequestUnsubscribeBoxArgs]) (*GetRequestUnsubscribeBoxMethodResult, error) {
	methodArgs := argsToInterfaceGetRequestUnsubscribeBox(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "get_request_unsubscribe_box",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return nil, err
	}

	typedResult := &GetRequestUnsubscribeBoxMethodResult{
		SendAppTransactionResult: *result,
	}

	if result.ABIReturn != nil {
		if val, ok := result.ABIReturn.([]interface{}); ok {
			typedResult.Return = val
		}
	}

	return typedResult, nil
}

// SendIsProposal calls the is_proposal ABI method and waits for confirmation.
func (c *Client) SendIsProposal(ctx context.Context, params algokit.CallParams[IsProposalArgs]) error {
	methodArgs := argsToInterfaceIsProposal(params.Args)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName:        "is_proposal",
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
		ExtraFee:          params.ExtraFee,
		StaticFee:         params.StaticFee,
		SendParams:        params.SendParams,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

// SendOpUp calls the op_up ABI method and waits for confirmation.
func (c *Client) SendOpUp(ctx context.Context) error {
	methodArgs := []interface{}(nil)

	result, err := c.AppClient.Send(ctx, algokit.AppCallSendParams{
		MethodName: "op_up",
		MethodArgs: methodArgs,
	})
	if err != nil {
		return err
	}

	_ = result
	return nil
}

func argsToInterfaceInitProposalContract(args InitProposalContractArgs) []interface{} {
	return []interface{}{
		args.Size,
	}
}

func argsToInterfaceLoadProposalContract(args LoadProposalContractArgs) []interface{} {
	return []interface{}{
		args.Offset,
		args.Data,
	}
}

func argsToInterfaceSetXgovManager(args SetXgovManagerArgs) []interface{} {
	return []interface{}{
		args.Manager,
	}
}

func argsToInterfaceSetPayor(args SetPayorArgs) []interface{} {
	return []interface{}{
		args.Payor,
	}
}

func argsToInterfaceSetXgovCouncil(args SetXgovCouncilArgs) []interface{} {
	return []interface{}{
		args.Council,
	}
}

func argsToInterfaceSetXgovSubscriber(args SetXgovSubscriberArgs) []interface{} {
	return []interface{}{
		args.Subscriber,
	}
}

func argsToInterfaceSetKycProvider(args SetKycProviderArgs) []interface{} {
	return []interface{}{
		args.Provider,
	}
}

func argsToInterfaceSetCommitteeManager(args SetCommitteeManagerArgs) []interface{} {
	return []interface{}{
		args.Manager,
	}
}

func argsToInterfaceSetXgovDaemon(args SetXgovDaemonArgs) []interface{} {
	return []interface{}{
		args.XgovDaemon,
	}
}

func argsToInterfaceConfigXgovRegistry(args ConfigXgovRegistryArgs) []interface{} {
	return []interface{}{
		args.Config,
	}
}

func argsToInterfaceSubscribeXgov(args SubscribeXgovArgs) []interface{} {
	return []interface{}{
		args.VotingAddress,
		args.Payment,
	}
}

func argsToInterfaceUnsubscribeAbsentee(args UnsubscribeAbsenteeArgs) []interface{} {
	return []interface{}{
		args.XgovAddress,
	}
}

func argsToInterfaceRequestSubscribeXgov(args RequestSubscribeXgovArgs) []interface{} {
	return []interface{}{
		args.XgovAddress,
		args.OwnerAddress,
		args.RelationType,
		args.Payment,
	}
}

func argsToInterfaceApproveSubscribeXgov(args ApproveSubscribeXgovArgs) []interface{} {
	return []interface{}{
		args.RequestID,
	}
}

func argsToInterfaceRejectSubscribeXgov(args RejectSubscribeXgovArgs) []interface{} {
	return []interface{}{
		args.RequestID,
	}
}

func argsToInterfaceRequestUnsubscribeXgov(args RequestUnsubscribeXgovArgs) []interface{} {
	return []interface{}{
		args.XgovAddress,
		args.OwnerAddress,
		args.RelationType,
		args.Payment,
	}
}

func argsToInterfaceApproveUnsubscribeXgov(args ApproveUnsubscribeXgovArgs) []interface{} {
	return []interface{}{
		args.RequestID,
	}
}

func argsToInterfaceRejectUnsubscribeXgov(args RejectUnsubscribeXgovArgs) []interface{} {
	return []interface{}{
		args.RequestID,
	}
}

func argsToInterfaceSetVotingAccount(args SetVotingAccountArgs) []interface{} {
	return []interface{}{
		args.XgovAddress,
		args.VotingAddress,
	}
}

func argsToInterfaceSubscribeProposer(args SubscribeProposerArgs) []interface{} {
	return []interface{}{
		args.Payment,
	}
}

func argsToInterfaceSetProposerKyc(args SetProposerKycArgs) []interface{} {
	return []interface{}{
		args.Proposer,
		args.KycStatus,
		args.KycExpiring,
	}
}

func argsToInterfaceDeclareCommittee(args DeclareCommitteeArgs) []interface{} {
	return []interface{}{
		args.CommitteeID,
		args.Size,
		args.Votes,
	}
}

func argsToInterfaceOpenProposal(args OpenProposalArgs) []interface{} {
	return []interface{}{
		args.Payment,
	}
}

func argsToInterfaceVoteProposal(args VoteProposalArgs) []interface{} {
	return []interface{}{
		args.ProposalID,
		args.XgovAddress,
		args.ApprovalVotes,
		args.RejectionVotes,
	}
}

func argsToInterfaceUnassignAbsenteeFromProposal(args UnassignAbsenteeFromProposalArgs) []interface{} {
	return []interface{}{
		args.ProposalID,
		args.Absentees,
	}
}

func argsToInterfacePayGrantProposal(args PayGrantProposalArgs) []interface{} {
	return []interface{}{
		args.ProposalID,
	}
}

func argsToInterfaceFinalizeProposal(args FinalizeProposalArgs) []interface{} {
	return []interface{}{
		args.ProposalID,
	}
}

func argsToInterfaceDropProposal(args DropProposalArgs) []interface{} {
	return []interface{}{
		args.ProposalID,
	}
}

func argsToInterfaceDepositFunds(args DepositFundsArgs) []interface{} {
	return []interface{}{
		args.Payment,
	}
}

func argsToInterfaceWithdrawFunds(args WithdrawFundsArgs) []interface{} {
	return []interface{}{
		args.Amount,
	}
}

func argsToInterfaceGetXgovBox(args GetXgovBoxArgs) []interface{} {
	return []interface{}{
		args.XgovAddress,
	}
}

func argsToInterfaceGetProposerBox(args GetProposerBoxArgs) []interface{} {
	return []interface{}{
		args.ProposerAddress,
	}
}

func argsToInterfaceGetRequestBox(args GetRequestBoxArgs) []interface{} {
	return []interface{}{
		args.RequestID,
	}
}

func argsToInterfaceGetRequestUnsubscribeBox(args GetRequestUnsubscribeBoxArgs) []interface{} {
	return []interface{}{
		args.RequestID,
	}
}

func argsToInterfaceIsProposal(args IsProposalArgs) []interface{} {
	return []interface{}{
		args.ProposalID,
	}
}

// Unmarshal helper for JSON decoding
func unmarshal(data []byte, v interface{}) error {
	return json.Unmarshal(data, v)
}

// Ensure fmt is used
var _ = fmt.Sprintf
