// Code generated by algokit-client-generator-go. DO NOT EDIT.
package xgovregistry

import (
	"context"

	algokit "github.com/kylebeee/algokit-utils-go"
)

// Composer builds atomic transaction groups for the XGovRegistry contract.
type Composer struct {
	client   *Client
	composer *algokit.TransactionComposer
}

// InitProposalContract adds a init_proposal_contract method call to the transaction group.
func (comp *Composer) InitProposalContract(ctx context.Context, params algokit.CallParams[InitProposalContractArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceInitProposalContract(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "init_proposal_contract" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// LoadProposalContract adds a load_proposal_contract method call to the transaction group.
func (comp *Composer) LoadProposalContract(ctx context.Context, params algokit.CallParams[LoadProposalContractArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceLoadProposalContract(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "load_proposal_contract" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// DeleteProposalContractBox adds a delete_proposal_contract_box method call to the transaction group.
func (comp *Composer) DeleteProposalContractBox(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "delete_proposal_contract_box" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// PauseRegistry adds a pause_registry method call to the transaction group.
func (comp *Composer) PauseRegistry(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "pause_registry" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// PauseProposals adds a pause_proposals method call to the transaction group.
func (comp *Composer) PauseProposals(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "pause_proposals" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// ResumeRegistry adds a resume_registry method call to the transaction group.
func (comp *Composer) ResumeRegistry(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "resume_registry" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// ResumeProposals adds a resume_proposals method call to the transaction group.
func (comp *Composer) ResumeProposals(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "resume_proposals" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SetXgovManager adds a set_xgov_manager method call to the transaction group.
func (comp *Composer) SetXgovManager(ctx context.Context, params algokit.CallParams[SetXgovManagerArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSetXgovManager(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "set_xgov_manager" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SetPayor adds a set_payor method call to the transaction group.
func (comp *Composer) SetPayor(ctx context.Context, params algokit.CallParams[SetPayorArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSetPayor(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "set_payor" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SetXgovCouncil adds a set_xgov_council method call to the transaction group.
func (comp *Composer) SetXgovCouncil(ctx context.Context, params algokit.CallParams[SetXgovCouncilArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSetXgovCouncil(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "set_xgov_council" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SetXgovSubscriber adds a set_xgov_subscriber method call to the transaction group.
func (comp *Composer) SetXgovSubscriber(ctx context.Context, params algokit.CallParams[SetXgovSubscriberArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSetXgovSubscriber(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "set_xgov_subscriber" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SetKycProvider adds a set_kyc_provider method call to the transaction group.
func (comp *Composer) SetKycProvider(ctx context.Context, params algokit.CallParams[SetKycProviderArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSetKycProvider(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "set_kyc_provider" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SetCommitteeManager adds a set_committee_manager method call to the transaction group.
func (comp *Composer) SetCommitteeManager(ctx context.Context, params algokit.CallParams[SetCommitteeManagerArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSetCommitteeManager(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "set_committee_manager" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SetXgovDaemon adds a set_xgov_daemon method call to the transaction group.
func (comp *Composer) SetXgovDaemon(ctx context.Context, params algokit.CallParams[SetXgovDaemonArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSetXgovDaemon(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "set_xgov_daemon" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// ConfigXgovRegistry adds a config_xgov_registry method call to the transaction group.
func (comp *Composer) ConfigXgovRegistry(ctx context.Context, params algokit.CallParams[ConfigXgovRegistryArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceConfigXgovRegistry(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "config_xgov_registry" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SubscribeXgov adds a subscribe_xgov method call to the transaction group.
func (comp *Composer) SubscribeXgov(ctx context.Context, params algokit.CallParams[SubscribeXgovArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSubscribeXgov(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "subscribe_xgov" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// UnsubscribeXgov adds a unsubscribe_xgov method call to the transaction group.
func (comp *Composer) UnsubscribeXgov(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "unsubscribe_xgov" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// UnsubscribeAbsentee adds a unsubscribe_absentee method call to the transaction group.
func (comp *Composer) UnsubscribeAbsentee(ctx context.Context, params algokit.CallParams[UnsubscribeAbsenteeArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceUnsubscribeAbsentee(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "unsubscribe_absentee" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// RequestSubscribeXgov adds a request_subscribe_xgov method call to the transaction group.
func (comp *Composer) RequestSubscribeXgov(ctx context.Context, params algokit.CallParams[RequestSubscribeXgovArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceRequestSubscribeXgov(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "request_subscribe_xgov" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// ApproveSubscribeXgov adds a approve_subscribe_xgov method call to the transaction group.
func (comp *Composer) ApproveSubscribeXgov(ctx context.Context, params algokit.CallParams[ApproveSubscribeXgovArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceApproveSubscribeXgov(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "approve_subscribe_xgov" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// RejectSubscribeXgov adds a reject_subscribe_xgov method call to the transaction group.
func (comp *Composer) RejectSubscribeXgov(ctx context.Context, params algokit.CallParams[RejectSubscribeXgovArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceRejectSubscribeXgov(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "reject_subscribe_xgov" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// RequestUnsubscribeXgov adds a request_unsubscribe_xgov method call to the transaction group.
func (comp *Composer) RequestUnsubscribeXgov(ctx context.Context, params algokit.CallParams[RequestUnsubscribeXgovArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceRequestUnsubscribeXgov(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "request_unsubscribe_xgov" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// ApproveUnsubscribeXgov adds a approve_unsubscribe_xgov method call to the transaction group.
func (comp *Composer) ApproveUnsubscribeXgov(ctx context.Context, params algokit.CallParams[ApproveUnsubscribeXgovArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceApproveUnsubscribeXgov(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "approve_unsubscribe_xgov" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// RejectUnsubscribeXgov adds a reject_unsubscribe_xgov method call to the transaction group.
func (comp *Composer) RejectUnsubscribeXgov(ctx context.Context, params algokit.CallParams[RejectUnsubscribeXgovArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceRejectUnsubscribeXgov(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "reject_unsubscribe_xgov" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SetVotingAccount adds a set_voting_account method call to the transaction group.
func (comp *Composer) SetVotingAccount(ctx context.Context, params algokit.CallParams[SetVotingAccountArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSetVotingAccount(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "set_voting_account" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SubscribeProposer adds a subscribe_proposer method call to the transaction group.
func (comp *Composer) SubscribeProposer(ctx context.Context, params algokit.CallParams[SubscribeProposerArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSubscribeProposer(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "subscribe_proposer" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// SetProposerKyc adds a set_proposer_kyc method call to the transaction group.
func (comp *Composer) SetProposerKyc(ctx context.Context, params algokit.CallParams[SetProposerKycArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceSetProposerKyc(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "set_proposer_kyc" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// DeclareCommittee adds a declare_committee method call to the transaction group.
func (comp *Composer) DeclareCommittee(ctx context.Context, params algokit.CallParams[DeclareCommitteeArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceDeclareCommittee(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "declare_committee" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// OpenProposal adds a open_proposal method call to the transaction group.
func (comp *Composer) OpenProposal(ctx context.Context, params algokit.CallParams[OpenProposalArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceOpenProposal(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "open_proposal" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// VoteProposal adds a vote_proposal method call to the transaction group.
func (comp *Composer) VoteProposal(ctx context.Context, params algokit.CallParams[VoteProposalArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceVoteProposal(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "vote_proposal" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// UnassignAbsenteeFromProposal adds a unassign_absentee_from_proposal method call to the transaction group.
func (comp *Composer) UnassignAbsenteeFromProposal(ctx context.Context, params algokit.CallParams[UnassignAbsenteeFromProposalArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceUnassignAbsenteeFromProposal(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "unassign_absentee_from_proposal" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// PayGrantProposal adds a pay_grant_proposal method call to the transaction group.
func (comp *Composer) PayGrantProposal(ctx context.Context, params algokit.CallParams[PayGrantProposalArgs]) (*Composer, error) {
	methodArgs := argsToInterfacePayGrantProposal(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "pay_grant_proposal" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// FinalizeProposal adds a finalize_proposal method call to the transaction group.
func (comp *Composer) FinalizeProposal(ctx context.Context, params algokit.CallParams[FinalizeProposalArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceFinalizeProposal(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "finalize_proposal" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// DropProposal adds a drop_proposal method call to the transaction group.
func (comp *Composer) DropProposal(ctx context.Context, params algokit.CallParams[DropProposalArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceDropProposal(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "drop_proposal" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// DepositFunds adds a deposit_funds method call to the transaction group.
func (comp *Composer) DepositFunds(ctx context.Context, params algokit.CallParams[DepositFundsArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceDepositFunds(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "deposit_funds" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// WithdrawFunds adds a withdraw_funds method call to the transaction group.
func (comp *Composer) WithdrawFunds(ctx context.Context, params algokit.CallParams[WithdrawFundsArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceWithdrawFunds(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "withdraw_funds" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// WithdrawBalance adds a withdraw_balance method call to the transaction group.
func (comp *Composer) WithdrawBalance(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "withdraw_balance" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// GetState adds a get_state method call to the transaction group.
func (comp *Composer) GetState(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "get_state" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// GetXgovBox adds a get_xgov_box method call to the transaction group.
func (comp *Composer) GetXgovBox(ctx context.Context, params algokit.CallParams[GetXgovBoxArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceGetXgovBox(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "get_xgov_box" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// GetProposerBox adds a get_proposer_box method call to the transaction group.
func (comp *Composer) GetProposerBox(ctx context.Context, params algokit.CallParams[GetProposerBoxArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceGetProposerBox(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "get_proposer_box" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// GetRequestBox adds a get_request_box method call to the transaction group.
func (comp *Composer) GetRequestBox(ctx context.Context, params algokit.CallParams[GetRequestBoxArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceGetRequestBox(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "get_request_box" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// GetRequestUnsubscribeBox adds a get_request_unsubscribe_box method call to the transaction group.
func (comp *Composer) GetRequestUnsubscribeBox(ctx context.Context, params algokit.CallParams[GetRequestUnsubscribeBoxArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceGetRequestUnsubscribeBox(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "get_request_unsubscribe_box" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// IsProposal adds a is_proposal method call to the transaction group.
func (comp *Composer) IsProposal(ctx context.Context, params algokit.CallParams[IsProposalArgs]) (*Composer, error) {
	methodArgs := argsToInterfaceIsProposal(params.Args)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "is_proposal" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:             comp.client.AppID(),
		Method:            method,
		MethodArgs:        methodArgs,
		Sender:            params.Sender,
		Signer:            params.Signer,
		Note:              params.Note,
		BoxReferences:     params.BoxReferences,
		AccountReferences: params.AccountReferences,
		AppReferences:     params.AppReferences,
		AssetReferences:   params.AssetReferences,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// OpUp adds a op_up method call to the transaction group.
func (comp *Composer) OpUp(ctx context.Context) (*Composer, error) {
	methodArgs := []interface{}(nil)

	method, err := comp.client.AppClient.AppSpec().Methods[0].ToABIMethod()
	for _, m := range comp.client.AppClient.AppSpec().Methods {
		if m.Name == "op_up" {
			method, err = m.ToABIMethod()
			break
		}
	}
	if err != nil {
		return nil, err
	}

	err = comp.composer.AddMethodCall(ctx, algokit.MethodCallParams{
		AppID:      comp.client.AppID(),
		Method:     method,
		MethodArgs: methodArgs,
	})
	if err != nil {
		return nil, err
	}
	return comp, nil
}

// Send executes the composed transaction group and waits for confirmation.
func (comp *Composer) Send(ctx context.Context) (*algokit.ComposerExecuteResult, error) {
	return comp.composer.Execute(ctx, 5)
}
