// Code generated by algokit-client-generator-go. DO NOT EDIT.
package xgovregistry

import (
	"github.com/algorand/go-algorand-sdk/v2/transaction"
	"github.com/algorand/go-algorand-sdk/v2/types"
	algokit "github.com/kylebeee/algokit-utils-go"
)

// TypedGlobalState is a generated struct type.
type TypedGlobalState struct {
	PausedRegistry        bool          `json:"paused_registry"`
	PausedProposals       bool          `json:"paused_proposals"`
	XgovManager           types.Address `json:"xgov_manager"`
	XgovPayor             types.Address `json:"xgov_payor"`
	XgovCouncil           types.Address `json:"xgov_council"`
	XgovSubscriber        types.Address `json:"xgov_subscriber"`
	KycProvider           types.Address `json:"kyc_provider"`
	CommitteeManager      types.Address `json:"committee_manager"`
	XgovDaemon            types.Address `json:"xgov_daemon"`
	XgovFee               uint64        `json:"xgov_fee"`
	ProposerFee           uint64        `json:"proposer_fee"`
	OpenProposalFee       uint64        `json:"open_proposal_fee"`
	DaemonOpsFundingBps   uint64        `json:"daemon_ops_funding_bps"`
	ProposalCommitmentBps uint64        `json:"proposal_commitment_bps"`
	MinRequestedAmount    uint64        `json:"min_requested_amount"`
	MaxRequestedAmount    [3]uint64     `json:"max_requested_amount"`
	DiscussionDuration    [4]uint64     `json:"discussion_duration"`
	VotingDuration        [4]uint64     `json:"voting_duration"`
	Quorum                [3]uint64     `json:"quorum"`
	WeightedQuorum        [3]uint64     `json:"weighted_quorum"`
	OutstandingFunds      uint64        `json:"outstanding_funds"`
	PendingProposals      uint64        `json:"pending_proposals"`
	CommitteeID           [32]byte      `json:"committee_id"`
	CommitteeMembers      uint64        `json:"committee_members"`
	CommitteeVotes        uint64        `json:"committee_votes"`
	AbsenceTolerance      uint64        `json:"absence_tolerance"`
	GovernancePeriod      uint64        `json:"governance_period"`
	CommitteeGracePeriod  uint64        `json:"committee_grace_period"`
	CommitteeLastAnchor   uint64        `json:"committee_last_anchor"`
}

// XGovBoxValue is a generated struct type.
type XGovBoxValue struct {
	VotingAddress     types.Address `json:"voting_address"`
	ToleratedAbsences uint64        `json:"tolerated_absences"`
	LastVoteTimestamp uint64        `json:"last_vote_timestamp"`
	SubscriptionRound uint64        `json:"subscription_round"`
}

// XGovRegistryConfig is a generated struct type.
type XGovRegistryConfig struct {
	XgovFee               uint64    `json:"xgov_fee"`
	ProposerFee           uint64    `json:"proposer_fee"`
	OpenProposalFee       uint64    `json:"open_proposal_fee"`
	DaemonOpsFundingBps   uint64    `json:"daemon_ops_funding_bps"`
	ProposalCommitmentBps uint64    `json:"proposal_commitment_bps"`
	MinRequestedAmount    uint64    `json:"min_requested_amount"`
	MaxRequestedAmount    [3]uint64 `json:"max_requested_amount"`
	DiscussionDuration    [4]uint64 `json:"discussion_duration"`
	VotingDuration        [4]uint64 `json:"voting_duration"`
	Quorum                [3]uint64 `json:"quorum"`
	WeightedQuorum        [3]uint64 `json:"weighted_quorum"`
	AbsenceTolerance      uint64    `json:"absence_tolerance"`
	GovernancePeriod      uint64    `json:"governance_period"`
	CommitteeGracePeriod  uint64    `json:"committee_grace_period"`
}

// XGovSubscribeRequestBoxValue is a generated struct type.
type XGovSubscribeRequestBoxValue struct {
	XgovAddr     types.Address `json:"xgov_addr"`
	OwnerAddr    types.Address `json:"owner_addr"`
	RelationType uint64        `json:"relation_type"`
}

// ProposerBoxValue is a generated struct type.
type ProposerBoxValue struct {
	ActiveProposal bool   `json:"active_proposal"`
	KycStatus      bool   `json:"kyc_status"`
	KycExpiring    uint64 `json:"kyc_expiring"`
}

// InitProposalContractArgs holds the arguments for the init_proposal_contract method.
type InitProposalContractArgs struct {
	Size uint64
}

// LoadProposalContractArgs holds the arguments for the load_proposal_contract method.
type LoadProposalContractArgs struct {
	Offset uint64
	Data   []byte
}

// SetXgovManagerArgs holds the arguments for the set_xgov_manager method.
type SetXgovManagerArgs struct {
	Manager types.Address
}

// SetPayorArgs holds the arguments for the set_payor method.
type SetPayorArgs struct {
	Payor types.Address
}

// SetXgovCouncilArgs holds the arguments for the set_xgov_council method.
type SetXgovCouncilArgs struct {
	Council types.Address
}

// SetXgovSubscriberArgs holds the arguments for the set_xgov_subscriber method.
type SetXgovSubscriberArgs struct {
	Subscriber types.Address
}

// SetKycProviderArgs holds the arguments for the set_kyc_provider method.
type SetKycProviderArgs struct {
	Provider types.Address
}

// SetCommitteeManagerArgs holds the arguments for the set_committee_manager method.
type SetCommitteeManagerArgs struct {
	Manager types.Address
}

// SetXgovDaemonArgs holds the arguments for the set_xgov_daemon method.
type SetXgovDaemonArgs struct {
	XgovDaemon types.Address
}

// ConfigXgovRegistryArgs holds the arguments for the config_xgov_registry method.
type ConfigXgovRegistryArgs struct {
	Config XGovRegistryConfig
}

// SubscribeXgovArgs holds the arguments for the subscribe_xgov method.
type SubscribeXgovArgs struct {
	VotingAddress types.Address
	Payment       transaction.TransactionWithSigner
}

// UnsubscribeAbsenteeArgs holds the arguments for the unsubscribe_absentee method.
type UnsubscribeAbsenteeArgs struct {
	XgovAddress types.Address
}

// RequestSubscribeXgovArgs holds the arguments for the request_subscribe_xgov method.
type RequestSubscribeXgovArgs struct {
	XgovAddress  types.Address
	OwnerAddress types.Address
	RelationType uint64
	Payment      transaction.TransactionWithSigner
}

// ApproveSubscribeXgovArgs holds the arguments for the approve_subscribe_xgov method.
type ApproveSubscribeXgovArgs struct {
	RequestID uint64
}

// RejectSubscribeXgovArgs holds the arguments for the reject_subscribe_xgov method.
type RejectSubscribeXgovArgs struct {
	RequestID uint64
}

// RequestUnsubscribeXgovArgs holds the arguments for the request_unsubscribe_xgov method.
type RequestUnsubscribeXgovArgs struct {
	XgovAddress  types.Address
	OwnerAddress types.Address
	RelationType uint64
	Payment      transaction.TransactionWithSigner
}

// ApproveUnsubscribeXgovArgs holds the arguments for the approve_unsubscribe_xgov method.
type ApproveUnsubscribeXgovArgs struct {
	RequestID uint64
}

// RejectUnsubscribeXgovArgs holds the arguments for the reject_unsubscribe_xgov method.
type RejectUnsubscribeXgovArgs struct {
	RequestID uint64
}

// SetVotingAccountArgs holds the arguments for the set_voting_account method.
type SetVotingAccountArgs struct {
	XgovAddress   types.Address
	VotingAddress types.Address
}

// SubscribeProposerArgs holds the arguments for the subscribe_proposer method.
type SubscribeProposerArgs struct {
	Payment transaction.TransactionWithSigner
}

// SetProposerKycArgs holds the arguments for the set_proposer_kyc method.
type SetProposerKycArgs struct {
	Proposer    types.Address
	KycStatus   bool
	KycExpiring uint64
}

// DeclareCommitteeArgs holds the arguments for the declare_committee method.
type DeclareCommitteeArgs struct {
	CommitteeID [32]byte
	Size        uint64
	Votes       uint64
}

// OpenProposalArgs holds the arguments for the open_proposal method.
type OpenProposalArgs struct {
	Payment transaction.TransactionWithSigner
}

// OpenProposalMethodResult holds the result of calling open_proposal.
type OpenProposalMethodResult struct {
	algokit.SendAppTransactionResult
	Return uint64
}

// VoteProposalArgs holds the arguments for the vote_proposal method.
type VoteProposalArgs struct {
	ProposalID     uint64
	XgovAddress    types.Address
	ApprovalVotes  uint64
	RejectionVotes uint64
}

// UnassignAbsenteeFromProposalArgs holds the arguments for the unassign_absentee_from_proposal method.
type UnassignAbsenteeFromProposalArgs struct {
	ProposalID uint64
	Absentees  []types.Address
}

// PayGrantProposalArgs holds the arguments for the pay_grant_proposal method.
type PayGrantProposalArgs struct {
	ProposalID uint64
}

// FinalizeProposalArgs holds the arguments for the finalize_proposal method.
type FinalizeProposalArgs struct {
	ProposalID uint64
}

// DropProposalArgs holds the arguments for the drop_proposal method.
type DropProposalArgs struct {
	ProposalID uint64
}

// DepositFundsArgs holds the arguments for the deposit_funds method.
type DepositFundsArgs struct {
	Payment transaction.TransactionWithSigner
}

// WithdrawFundsArgs holds the arguments for the withdraw_funds method.
type WithdrawFundsArgs struct {
	Amount uint64
}

// GetStateMethodResult holds the result of calling get_state.
type GetStateMethodResult struct {
	algokit.SendAppTransactionResult
	Return TypedGlobalState
}

// GetXgovBoxArgs holds the arguments for the get_xgov_box method.
type GetXgovBoxArgs struct {
	XgovAddress types.Address
}

// GetXgovBoxMethodResult holds the result of calling get_xgov_box.
type GetXgovBoxMethodResult struct {
	algokit.SendAppTransactionResult
	Return []interface{}
}

// GetProposerBoxArgs holds the arguments for the get_proposer_box method.
type GetProposerBoxArgs struct {
	ProposerAddress types.Address
}

// GetProposerBoxMethodResult holds the result of calling get_proposer_box.
type GetProposerBoxMethodResult struct {
	algokit.SendAppTransactionResult
	Return []interface{}
}

// GetRequestBoxArgs holds the arguments for the get_request_box method.
type GetRequestBoxArgs struct {
	RequestID uint64
}

// GetRequestBoxMethodResult holds the result of calling get_request_box.
type GetRequestBoxMethodResult struct {
	algokit.SendAppTransactionResult
	Return []interface{}
}

// GetRequestUnsubscribeBoxArgs holds the arguments for the get_request_unsubscribe_box method.
type GetRequestUnsubscribeBoxArgs struct {
	RequestID uint64
}

// GetRequestUnsubscribeBoxMethodResult holds the result of calling get_request_unsubscribe_box.
type GetRequestUnsubscribeBoxMethodResult struct {
	algokit.SendAppTransactionResult
	Return []interface{}
}

// IsProposalArgs holds the arguments for the is_proposal method.
type IsProposalArgs struct {
	ProposalID uint64
}
